# Generated by Django 2.2.13 on 2021-03-01 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstorder', '0002_remove_orders_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='order',
            field=models.CharField(default='abc', max_length=30, verbose_name='订单内容'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderid',
            field=models.CharField(default='abc', max_length=30, verbose_name='订单id'),
        ),
    ]
